[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
# Porta Railway (auto-assign)
PORT = "$PORT"

# Python
PYTHONPATH = "."
PYTHONUNBUFFERED = "1"