[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
# Porta padrão Railway
PORT = "8080"

# Python
PYTHONPATH = "."
PYTHONUNBUFFERED = "1"

# Configurações do projeto
WEBHOOK_PORT = "8080"