[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
# Porta Railway (auto-assign)
WEBHOOK_PORT = "$PORT"

# Python 
PYTHONPATH = "."
PYTHONUNBUFFERED = "1"

# Configurações essenciais
NODE_ENV = "production"