[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 2

[environments.production.variables]
PYTHONPATH = "."
PYTHONUNBUFFERED = "1"